apiVersion: 1

datasources:
  - name: PostgresDSP
    uid: dsp_postgres
    type: postgres
    access: proxy
    url: db:5432
    user: $POSTGRES_USER
    isDefault: true
    jsonData:
      database: $POSTGRES_DB
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
    editable: true
